version: '3.8'
services:
  weather:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/weather_app
    volumes:
      - .:/app
    restart: always

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/weather_app
    restart: on-failure

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - weather_data_app:/data/db
    restart: always

volumes:
  weather_data_app:
