FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY /static/css /app/static/css
COPY /templates/ /app/templates
COPY app.py test_app.py /app/
CMD ["pytest"]
