{{- if .Values.mongo.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongo.auth.existingSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "applic.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  username: {{ .Values.mongo.auth.rootUser | b64enc | quote }}
  password: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}
