apiVersion: v1
kind: Service
metadata:
  name: {{ include "applic.name" . }}-mongo
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "applic.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mongodb
spec:
  type: {{ .Values.mongo.service.type }}
  ports:
    - port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "applic.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mongodb
