apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "applic.name" . }}-mongo
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "applic.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mongodb
spec:
  accessModes: {{ toYaml .Values.mongo.storage.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.mongo.storage.size }}
  storageClassName: {{ .Values.mongo.storage.storageClass | quote }}
