apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-key
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  api-key: {{ .Values.apiKey | b64enc | quote }}
  gpt-key: {{ .Values.gptKey | b64enc | quote }}